### ISSUE TITLE
Preference on admin form

### ISSUE THREAD

**Issue by vjacquemin-sqli** [pmclain/magento2-tfa#5]
Hello,

I have downloaded your Magento 2 module and it works. However, I noticed the TODO comment in your di.xml. I think a preference is not a good way to change admin form behaviour. Indeed, if there is a Magento update which change admin form, your module will have priority and could produce issues.

Maybe you can preference Magento\Framework\Data\Form and just check if it receive action "adminhtml/system_account/save" (then it's the admin account form). If yes, you add fields. If no, you do nothing.

By this way, you just have a condition on admin account form, and if there is a Magento update, initial fields are not impacted.

Sincerely.

**Comment by pmclain** [comment]
Adding a preference for `Magento\Framework\Data\Form` would be much more invasive than the current preference. It would widen the scope of potential breaking changes within core and 3rd party modules well beyond fields contained in the admin block.

**Comment by vjacquemin-sqli** [comment]
Yes, but the condition on the action can prevent behaviour. But it's true, that's not a good way to do a preference.

Otherwise, you can move your block and create another form with a custom route and add an option in admin dropdown menu (on right top).

**Comment by pmclain** [comment]
The style form used here is deprecated and will eventually be replaced with a uiComponent implementation [ref](https://github.com/magento/magento2/pull/13602). Until then, the preference will have to remain.
