### ISSUE TITLE
Multiple stores - Authenticator Overwrites Existing

### ISSUE THREAD

**Issue by jeffmalterre** [pmclain/magento2-tfa#6]
Site A - Installed and scanned code, everything works.
Site B - Installed and scanned code, overwrote existing key in google authenticator.

How should I proceed?

**Comment by pmclain** [comment]
The company name included in the QR code was hard coded. I've updated this to use the admin base url instead, so it should be unique for each store. I also added some console commands for disabling TFA for user(s). https://github.com/pmclain/magento2-tfa/releases/tag/1.1.0

**Comment by jeffmalterre** [comment]
Works perfectly, tyvm good job 👍
